---
mongodb_backup_cron_name:       'Backup MongoDB databases'
mongodb_backup_frequency:       'daily'
mongodb_backup_lifetime_days:   14
mongodb_backup_file_prefix:     'mongodb_backup'
mongodb_backup_dir:             '/var/backup/mongodb_backup'
mongodb_backup_script_dir:      '/etc/mongodb_backup'
mongodb_backup_script_filename: 'mongodb_backup.sh'